# See docs/examples here:
# http://doc.gitlab.com/ce/ci/quick_start/README.html
# http://doc.gitlab.com/ce/ci/yaml/README.html
stages:
  - build
  - test
  - bench

image: golang:1.9

variables:
  PREFIX: "wojtekz"
  WORKSPACE: "/workspace"
#  if CMDDIR == $WORKSPACE/src/$NAME then set CMDDIR="."
  CMDDIR: "cmd/imageproxy"


build-golang-1.9:
  stage: build
  tags:
   - test-ci
  script:
    - export GOPATH=$GOPATH:$WORKSPACE
    - mkdir -p $WORKSPACE/src/$NAME
    - cd $WORKSPACE/src/$NAME
    - pwd
    - ln -s $CI_PROJECT_DIR .
    - cd $(basename $CI_PROJECT_DIR)
    - pwd
    - cd $CMDDIR
    - pwd
    - go build

test-golang-1.9:
  stage: test
  tags:
   - test-ci
  script:
    - export GOPATH=$GOPATH:$WORKSPACE
    - mkdir -p $WORKSPACE/src/$NAME
    - cd $WORKSPACE/src/$NAME
    - ln -s $CI_PROJECT_DIR .
    - cd $(basename $CI_PROJECT_DIR)
    - go test -v -cover


bench-golang-1.9:
  stage: bench
  tags:
   - test-ci
  script:
    - export GOPATH=$GOPATH:$WORKSPACE
    - mkdir -p $WORKSPACE/src/$NAME
    - cd $WORKSPACE/src/$NAME
    - ln -s $CI_PROJECT_DIR .
    - cd $(basename $CI_PROJECT_DIR)
    - go test -bench .


test-golang-latest:
  image: golang:latest
  stage: test
  tags:
   - test-ci
  script:
    - export GOPATH=$GOPATH:$WORKSPACE
    - mkdir -p $WORKSPACE/src/$NAME
    - cd $WORKSPACE/src/$NAME
    - ln -s $CI_PROJECT_DIR .
    - cd $(basename $CI_PROJECT_DIR)
    - go version
    - go test -v -cover
