language: go

go:
  - 1.8
  - tip

sudo: false

install:
  - go get -v -t -d github.com/wojtekzw/imageproxy/...

script:
  - go test -v $(go list github.com/wojtekzw/imageproxy/... | grep -v vendor | grep -v tools)
