
---

- name: Build and test Linux & MacOS binary
  hosts: ls
  gather_facts: no
  vars:
    base_dir: "/home/wzwiefka"
    local_dir: "/Users/wzwiefka"
    imageproxy_dir: "{{ local_dir }}/Documents/goext/src/github.com/wojtekzw/imageproxy"
    imageproxy_cmd_dir: "{{ imageproxy_dir}}//cmd/imageproxy"
    golang_ldflags: "-X main.BuildDate=`date -u '+%Y-%m-%d_%I:%M:%S%p'` -X main.GitHash=`git rev-parse HEAD` -X main.Version=0.5"

  tasks:
  - name: Test imageproxy binary
    run_once: true
    local_action:  shell cd {{ imageproxy_dir }}; go test -v -tags novips
    tags:
      - build
      - new_binary
      - macos


  - name: Build imageproxy Linux binary
    run_once: true
    local_action: shell cd {{ imageproxy_cmd_dir }}; GOOS=linux GOARCH=amd64  go build -tags novips -ldflags "{{ golang_ldflags }}" -o builds/imageproxy-linux
    tags:
      - build
      - new_binary

  - name: Build imageproxy MaxOS binary
    run_once: true
    local_action: shell cd {{ imageproxy_cmd_dir }}; GOOS=darwin GOARCH=amd64  go build -tags novips -ldflags "{{ golang_ldflags }}" -o builds/imageproxy-macos
    tags:
      - build
      - macos


- name: Deploy logserver binary and/or config - serialy
  hosts: ls
  #  deploy serialy 1 by 1
  serial: 1
#  gather_facts: no


  vars:
    base_dir: "/home/wzwiefka"
    local_dir: "/Users/wzwiefka"
    imageproxy_dir: "{{ local_dir }}/Documents/goext/src/github.com/wojtekzw/imageproxy"
    imageproxy_cmd_dir: "{{ imageproxy_dir}}//cmd/imageproxy"


  tasks:
  - name: Stop imageproxy
    supervisorctl:
      name: imageproxy
      state: stopped
      config: "{{ base_dir }}/supervisord.conf"
    tags:
      - new_config
      - binary
      - new_binary

  - name: Copy binary imageproxy
    copy:
      src: "{{ imageproxy_cmd_dir }}/builds/imageproxy-linux"
      dest: "{{ base_dir }}/bin-linux/imageproxy"
      backup: yes
    tags:
      - binary
      - new_binary

#  - name: Copy config files
#    copy:
#      src: "{{ logserver_dir }}/logserver-prod.yml"
#      dest: "{{ base_dir }}/etc/logserver/logserver-prod.yml"
#      backup: yes
#    tags:
#      - new_config


  - name: Restart imageproxy
    supervisorctl:
      name: imageproxy
      state: started
      config: "{{ base_dir }}/supervisord.conf"
    tags:
      - new_config
      - binary
      - new_binary


